-- ALTER USER 'crime'@'localhost' IDENTIFIED with mysql_native_password BY 'Crime1q2w3e4r!';

DROP TABLE SEATTLE_CRIME;

USE CRIMEDB;

CREATE TABLE SEATTLE_CRIME(
    REP_NUM INT AUTO_INCREMENT PRIMARY KEY,
    OCC_DATE VARCHAR(32),
    OCC_TIME INT,
    REP_DATE VARCHAR(32),
    REP_TIME INT,
    SUB_CATE VARCHAR(128),
    PRI_DESC VARCHAR(128),
    PRECINCT VARCHAR(64),
    SECTOR VARCHAR(8),
    BEAT VARCHAR(8),
    NEIGHBOR VARCHAR(128)
);

COMMIT;

-- INSERT INTO SEATTLE_CRIME VALUES(REP_NUM,'01/01/2008', 2330, '01/02/2008', 1819, 'CAR PROWL', 'THEFT-CARPROWL', 'SOUTHWEST', 'F', 'F3', 'SOUTH PARK') 